### ISSUE TITLE
Time spend not getting passed date

### ISSUE THREAD

**Issue by rigatron1986** [cgwire/gazu#258] opened 2022-09-27 17:34 UTC
When i do 
time_spent = gazu.task.get_time_spent(_task, '2022-08-20')
this gives me all the time spend for the entire task , Can we retain this and add another to get time spend on a single day.

**Comment by EvanBldy** [comment] 2022-10-18 13:16
Hi @rigatron1986,
Thanks for the report ! 
The problem is on Zou side, the date argument was not used.
It should be fixed in this PR https://github.com/cgwire/zou/pull/535. It will be in the next release, when you have time to try this and if it's okay please close the issue :) 
Have a nice day

**Comment by rigatron1986** [comment] 2022-10-18 13:24
Yes this seems to look great.. but can we also have the previous one.. where we get the total time for the task.

**Closed** 2022-10-20 15:18 UTC
Labels: bug
