### ISSUE TITLE
Image format when downloading 

### ISSUE THREAD

**Issue by developer-cube-creative** [cgwire/gazu#39] opened 2018-10-29 14:13 UTC
Hello,

We try to put posted images in our pipeline.
We use the `gazu.client.download(url, download_path)` function.

Problem is
- .png file was uploaded
- .png file is downloaded
- .png file is not readable in Photoshop (or Qt based applications) **unless you rename the file to .jpg**

Maybe re-encoding is happening at some point ?

Thanks

**Comment by frankrousseau** [comment] 2018-12-19 12:21
I don't know what to do. When I use `imghdr` from python standard library it tells me it's a `.png` file. I can open with Gimp too. Did you try with another software than photoshop? What happens when you download the picture from the browser?

https://docs.python.org/2/library/imghdr.html

**Comment by frankrousseau** [comment] 2018-12-19 13:15
I made a mistake it works too with Gazu.

**Comment by Steakashi** [comment] 2018-12-19 16:56
We tried to open the file with djv_view (doesn't work), the default Windows photo viewer (works), paint (works) and XnView (works too). The main problem is that the file can't be displayed in our Qt based applications.
Also, when we try to download the picture from the browser (Mozilla Firefox here), it automatically add a jpg extension at the end of the file. If we remove it, we face the same problems again.

**Comment by BigRoy** [comment] 2019-05-08 08:06
> We tried to open the file with djv_view (doesn't work), the default Windows photo viewer (works), paint (works) and XnView (works too). The main problem is that the file can't be displayed in our Qt based applications.

I can confirm this is still the case, however if I save the file as `.jpg` then djv_view is able to open it. As such my assumption is that the downloaded file is actually a JPEG file.

Looking at [this link](https://web.archive.org/web/20090302032444/http://www.mikekunz.com/image_file_header.html) it does indeed seem to be a JPEG file since the beginning of the file starts with the magic JPEG numbers. 

 > Also, when we try to download the picture from the browser (Mozilla Firefox here), it automatically add a jpg extension at the end of the file. If we remove it, we face the same problems again.

This I can also confirm - when trying to save the image straight from the website it will try to append `.jpg` at the end, making `{id}.png.jpg` and magically djv_view can read it as it makes the right assumption that it is a JPEG. This downloaded file also has the magic JPEG numbers and thus can be assumed to be JPEG.

As such, the files online are incorrectly given the extension `.png` :) And in the meantime from Gazu just make sure you save as `.jpg` if you want to be fully correct.

**Comment by BigRoy** [comment] 2019-05-08 08:15
Had a quick look where this issue originates from, seems to be in `zou`. Specifically the saving with `PIL.Image` doesn't explicitly state that it needs to be `PNG` here: https://github.com/BigRoy/zou/blob/fc268a98c10ead260e67d0eb599a5ad912a35a93/zou/app/utils/thumbnail.py#L37

Reference source describing that it is required to explicitly state PNG: https://stackoverflow.com/a/19651233/1838864

@frankrousseau Since you're enforcing the output extension to be `.png` I'd recommend forcing PNG codec for all ".save()" calls.

**Comment by frankrousseau** [comment] 2019-05-08 10:59
Thank you for the information. I will handle this problem soon. With your information, it should be easy to fix.

**Comment by BigRoy** [comment] 2019-05-13 15:19
I noticed [this commit](https://github.com/cgwire/zou/pull/151/commits/817ea75e436588d159b8015f5d46d79c924ce120) secretly being pushed in with this PR: https://github.com/cgwire/zou/pull/151/files which should mean that for live instances that receive this update the next uploaded PNG should have the proposed fixes.

However note that the fix is not applied here:
- https://github.com/cgwire/zou/blob/14d5fb66b1a93765823acfc103eb09f91fc39024/zou/app/utils/thumbnail.py#L23
- https://github.com/cgwire/zou/blob/14d5fb66b1a93765823acfc103eb09f91fc39024/zou/app/utils/thumbnail.py#L76
- https://github.com/cgwire/zou/blob/831a14610ed5d2794b31505d5da55fe3c1593454/zou/app/utils/movie_utils.py#L15

I'm not sure if it should be in all those lines - just stating that it might still be missing for those @frankrousseau - or did you test run locally?

Especially pointing this out since the commit was merged with another PR that doesn't mention it, so maybe it crawled in their without testing by mistake.

**Comment by frankrousseau** [comment] 2019-05-13 16:24
Sorry for including this commit with other changes without mentioning it into the PR. 

About the lines you mention, two of them are pure Flask function, so the change you mention doesn't apply. For the 76 line, it's missing. Thank you for pointing it.

I didn't run tests about it. I had in mind to ask you once this version deployed on your instance.

**Comment by frankrousseau** [comment] 2019-05-16 17:17
It should be fixed. Can you try again?

**Comment by BigRoy** [comment] 2019-05-20 12:54
Just uploaded a new preview file, downloaded it through the browser (it defaults correctly to `.png`) and also djv_view opened it without issue as `png` plus it seems to have a valid PNG format file signature as the header so this should be all good.

Also quickly ran a test download of this same file through gazu.

```python
# top method is pseudocode for something I have around to get current task in pipeline
task = _get_cgwire_task()
comment = gazu.task.get_last_comment_for_task(task)
preview = comment["previews"][0]
gazu.files.download_preview_file(preview, "/path/to/target.png")
```

Seems to work fine! 

Note that `gazu.files.download_preview_file`  uses `gazu.client.download` internally so it should behave the same and be fixed for @developer-cube-creative original case too.

---

A bit off-topic @frankrousseau any reason why my comment does have `previews`  in its returned data but the `preview_file_id` is set to `None`? Is that old deprecated data?

**Comment by frankrousseau** [comment] 2019-05-27 17:17
Yes `preview_file_id` is a deprecated field.

**Closed** 2019-06-03 21:24 UTC
Labels: bug
